package com.itcast.domain.export;

import java.math.BigDecimal;
import java.util.Date;

public class Export {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.input_date
     *
     * @mbg.generated
     */
    private Date inputDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.contract_ids
     *
     * @mbg.generated
     */
    private String contractIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.customer_contract
     *
     * @mbg.generated
     */
    private String customerContract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.lcno
     *
     * @mbg.generated
     */
    private String lcno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.consignee
     *
     * @mbg.generated
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.marks
     *
     * @mbg.generated
     */
    private String marks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.shipment_port
     *
     * @mbg.generated
     */
    private String shipmentPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.destination_port
     *
     * @mbg.generated
     */
    private String destinationPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.transport_mode
     *
     * @mbg.generated
     */
    private String transportMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.price_condition
     *
     * @mbg.generated
     */
    private String priceCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.box_nums
     *
     * @mbg.generated
     */
    private Long boxNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.gross_weights
     *
     * @mbg.generated
     */
    private BigDecimal grossWeights;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.measurements
     *
     * @mbg.generated
     */
    private BigDecimal measurements;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.state
     *
     * @mbg.generated
     */
    private Long state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.pro_num
     *
     * @mbg.generated
     */
    private Integer proNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.ext_num
     *
     * @mbg.generated
     */
    private Integer extNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.create_dept
     *
     * @mbg.generated
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_export.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.id
     *
     * @return the value of co_export.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.id
     *
     * @param id the value for co_export.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.input_date
     *
     * @return the value of co_export.input_date
     *
     * @mbg.generated
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.input_date
     *
     * @param inputDate the value for co_export.input_date
     *
     * @mbg.generated
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.contract_ids
     *
     * @return the value of co_export.contract_ids
     *
     * @mbg.generated
     */
    public String getContractIds() {
        return contractIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.contract_ids
     *
     * @param contractIds the value for co_export.contract_ids
     *
     * @mbg.generated
     */
    public void setContractIds(String contractIds) {
        this.contractIds = contractIds == null ? null : contractIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.customer_contract
     *
     * @return the value of co_export.customer_contract
     *
     * @mbg.generated
     */
    public String getCustomerContract() {
        return customerContract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.customer_contract
     *
     * @param customerContract the value for co_export.customer_contract
     *
     * @mbg.generated
     */
    public void setCustomerContract(String customerContract) {
        this.customerContract = customerContract == null ? null : customerContract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.lcno
     *
     * @return the value of co_export.lcno
     *
     * @mbg.generated
     */
    public String getLcno() {
        return lcno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.lcno
     *
     * @param lcno the value for co_export.lcno
     *
     * @mbg.generated
     */
    public void setLcno(String lcno) {
        this.lcno = lcno == null ? null : lcno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.consignee
     *
     * @return the value of co_export.consignee
     *
     * @mbg.generated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.consignee
     *
     * @param consignee the value for co_export.consignee
     *
     * @mbg.generated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.marks
     *
     * @return the value of co_export.marks
     *
     * @mbg.generated
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.marks
     *
     * @param marks the value for co_export.marks
     *
     * @mbg.generated
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.shipment_port
     *
     * @return the value of co_export.shipment_port
     *
     * @mbg.generated
     */
    public String getShipmentPort() {
        return shipmentPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.shipment_port
     *
     * @param shipmentPort the value for co_export.shipment_port
     *
     * @mbg.generated
     */
    public void setShipmentPort(String shipmentPort) {
        this.shipmentPort = shipmentPort == null ? null : shipmentPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.destination_port
     *
     * @return the value of co_export.destination_port
     *
     * @mbg.generated
     */
    public String getDestinationPort() {
        return destinationPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.destination_port
     *
     * @param destinationPort the value for co_export.destination_port
     *
     * @mbg.generated
     */
    public void setDestinationPort(String destinationPort) {
        this.destinationPort = destinationPort == null ? null : destinationPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.transport_mode
     *
     * @return the value of co_export.transport_mode
     *
     * @mbg.generated
     */
    public String getTransportMode() {
        return transportMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.transport_mode
     *
     * @param transportMode the value for co_export.transport_mode
     *
     * @mbg.generated
     */
    public void setTransportMode(String transportMode) {
        this.transportMode = transportMode == null ? null : transportMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.price_condition
     *
     * @return the value of co_export.price_condition
     *
     * @mbg.generated
     */
    public String getPriceCondition() {
        return priceCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.price_condition
     *
     * @param priceCondition the value for co_export.price_condition
     *
     * @mbg.generated
     */
    public void setPriceCondition(String priceCondition) {
        this.priceCondition = priceCondition == null ? null : priceCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.remark
     *
     * @return the value of co_export.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.remark
     *
     * @param remark the value for co_export.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.box_nums
     *
     * @return the value of co_export.box_nums
     *
     * @mbg.generated
     */
    public Long getBoxNums() {
        return boxNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.box_nums
     *
     * @param boxNums the value for co_export.box_nums
     *
     * @mbg.generated
     */
    public void setBoxNums(Long boxNums) {
        this.boxNums = boxNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.gross_weights
     *
     * @return the value of co_export.gross_weights
     *
     * @mbg.generated
     */
    public BigDecimal getGrossWeights() {
        return grossWeights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.gross_weights
     *
     * @param grossWeights the value for co_export.gross_weights
     *
     * @mbg.generated
     */
    public void setGrossWeights(BigDecimal grossWeights) {
        this.grossWeights = grossWeights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.measurements
     *
     * @return the value of co_export.measurements
     *
     * @mbg.generated
     */
    public BigDecimal getMeasurements() {
        return measurements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.measurements
     *
     * @param measurements the value for co_export.measurements
     *
     * @mbg.generated
     */
    public void setMeasurements(BigDecimal measurements) {
        this.measurements = measurements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.state
     *
     * @return the value of co_export.state
     *
     * @mbg.generated
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.state
     *
     * @param state the value for co_export.state
     *
     * @mbg.generated
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.pro_num
     *
     * @return the value of co_export.pro_num
     *
     * @mbg.generated
     */
    public Integer getProNum() {
        return proNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.pro_num
     *
     * @param proNum the value for co_export.pro_num
     *
     * @mbg.generated
     */
    public void setProNum(Integer proNum) {
        this.proNum = proNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.ext_num
     *
     * @return the value of co_export.ext_num
     *
     * @mbg.generated
     */
    public Integer getExtNum() {
        return extNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.ext_num
     *
     * @param extNum the value for co_export.ext_num
     *
     * @mbg.generated
     */
    public void setExtNum(Integer extNum) {
        this.extNum = extNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.create_by
     *
     * @return the value of co_export.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.create_by
     *
     * @param createBy the value for co_export.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.create_dept
     *
     * @return the value of co_export.create_dept
     *
     * @mbg.generated
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.create_dept
     *
     * @param createDept the value for co_export.create_dept
     *
     * @mbg.generated
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept == null ? null : createDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.create_time
     *
     * @return the value of co_export.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.create_time
     *
     * @param createTime the value for co_export.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.company_id
     *
     * @return the value of co_export.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.company_id
     *
     * @param companyId the value for co_export.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_export.company_name
     *
     * @return the value of co_export.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_export.company_name
     *
     * @param companyName the value for co_export.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}