package com.itcast.domain.export;

import java.math.BigDecimal;

public class ExtEproduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.export_product_id
     *
     * @mbg.generated
     */
    private String exportProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.export_id
     *
     * @mbg.generated
     */
    private String exportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.factory_id
     *
     * @mbg.generated
     */
    private String factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.product_no
     *
     * @mbg.generated
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.product_image
     *
     * @mbg.generated
     */
    private String productImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.product_desc
     *
     * @mbg.generated
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.cnumber
     *
     * @mbg.generated
     */
    private Long cnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.packing_unit
     *
     * @mbg.generated
     */
    private String packingUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.order_no
     *
     * @mbg.generated
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_ext_eproduct.product_request
     *
     * @mbg.generated
     */
    private String productRequest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.id
     *
     * @return the value of co_ext_eproduct.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.id
     *
     * @param id the value for co_ext_eproduct.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.export_product_id
     *
     * @return the value of co_ext_eproduct.export_product_id
     *
     * @mbg.generated
     */
    public String getExportProductId() {
        return exportProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.export_product_id
     *
     * @param exportProductId the value for co_ext_eproduct.export_product_id
     *
     * @mbg.generated
     */
    public void setExportProductId(String exportProductId) {
        this.exportProductId = exportProductId == null ? null : exportProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.export_id
     *
     * @return the value of co_ext_eproduct.export_id
     *
     * @mbg.generated
     */
    public String getExportId() {
        return exportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.export_id
     *
     * @param exportId the value for co_ext_eproduct.export_id
     *
     * @mbg.generated
     */
    public void setExportId(String exportId) {
        this.exportId = exportId == null ? null : exportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.factory_id
     *
     * @return the value of co_ext_eproduct.factory_id
     *
     * @mbg.generated
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.factory_id
     *
     * @param factoryId the value for co_ext_eproduct.factory_id
     *
     * @mbg.generated
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId == null ? null : factoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.product_no
     *
     * @return the value of co_ext_eproduct.product_no
     *
     * @mbg.generated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.product_no
     *
     * @param productNo the value for co_ext_eproduct.product_no
     *
     * @mbg.generated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.product_image
     *
     * @return the value of co_ext_eproduct.product_image
     *
     * @mbg.generated
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.product_image
     *
     * @param productImage the value for co_ext_eproduct.product_image
     *
     * @mbg.generated
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage == null ? null : productImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.product_desc
     *
     * @return the value of co_ext_eproduct.product_desc
     *
     * @mbg.generated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.product_desc
     *
     * @param productDesc the value for co_ext_eproduct.product_desc
     *
     * @mbg.generated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.cnumber
     *
     * @return the value of co_ext_eproduct.cnumber
     *
     * @mbg.generated
     */
    public Long getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.cnumber
     *
     * @param cnumber the value for co_ext_eproduct.cnumber
     *
     * @mbg.generated
     */
    public void setCnumber(Long cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.packing_unit
     *
     * @return the value of co_ext_eproduct.packing_unit
     *
     * @mbg.generated
     */
    public String getPackingUnit() {
        return packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.packing_unit
     *
     * @param packingUnit the value for co_ext_eproduct.packing_unit
     *
     * @mbg.generated
     */
    public void setPackingUnit(String packingUnit) {
        this.packingUnit = packingUnit == null ? null : packingUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.price
     *
     * @return the value of co_ext_eproduct.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.price
     *
     * @param price the value for co_ext_eproduct.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.amount
     *
     * @return the value of co_ext_eproduct.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.amount
     *
     * @param amount the value for co_ext_eproduct.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.order_no
     *
     * @return the value of co_ext_eproduct.order_no
     *
     * @mbg.generated
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.order_no
     *
     * @param orderNo the value for co_ext_eproduct.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.company_id
     *
     * @return the value of co_ext_eproduct.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.company_id
     *
     * @param companyId the value for co_ext_eproduct.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.company_name
     *
     * @return the value of co_ext_eproduct.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.company_name
     *
     * @param companyName the value for co_ext_eproduct.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_ext_eproduct.product_request
     *
     * @return the value of co_ext_eproduct.product_request
     *
     * @mbg.generated
     */
    public String getProductRequest() {
        return productRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_ext_eproduct.product_request
     *
     * @param productRequest the value for co_ext_eproduct.product_request
     *
     * @mbg.generated
     */
    public void setProductRequest(String productRequest) {
        this.productRequest = productRequest == null ? null : productRequest.trim();
    }
}