package com.itcast.dao.cargo;

import com.itcast.domain.cargo.Invoice;
import com.itcast.domain.cargo.InvoiceExample;
import java.util.List;

public interface InvoiceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String invoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    int insert(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    int insertSelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    List<Invoice> selectByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    Invoice selectByPrimaryKey(String invoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_invoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Invoice record);
}