package com.itcast.dao.cargo;

import com.itcast.domain.cargo.PakList;
import com.itcast.domain.cargo.PakListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PakListDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    long countByExample(PakListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int deleteByExample(PakListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String packingListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int insert(PakList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int insertSelective(PakList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    List<PakList> selectByExample(PakListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    PakList selectByPrimaryKey(String packingListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PakList record, @Param("example") PakListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PakList record, @Param("example") PakListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PakList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PakList record);
}