package com.itcast.dao.export;

import com.itcast.domain.export.Export;

public interface ExportDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    int insert(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    int insertSelective(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    Export selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Export record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Export record);
}