package com.itcast.dao.export;

import com.itcast.domain.export.ExportProduct;

public interface ExportProductDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    int insert(ExportProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    int insertSelective(ExportProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    ExportProduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExportProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_export_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExportProduct record);
}